### PR TITLE
Add component level test suite for Explorer APIs

### PR DESCRIPTION
**Pull request by CaretCake**
@jordanCain If you could please provide feedback on these test cases from the perspective of the Explorer APIs squad, that would be great. If there is another level of concurrency that you feel would be beneficial to define as a starting point for all users of these tests, other endpoints that we need to be testing, or specific more complicated test cases that might be beneficial (for example, a sequence of endpoints, etc). As a note, we do already have plans to get into testing with different file sizes, methods, etc for comparison as part of another issue (https://github.com/zowe/zowe-install-packaging/issues/633).

This work should close https://github.com/zowe/zowe-install-packaging/issues/644

### CODE REVIEW

**Review by jackjia-ibm — APPROVED** [review]
Looks good to me! Thanks for the work and I do very much like your clean coding style.

**Comment by jordanCain** [comment]
@CaretCake The test cases thus far look great, I have a couple of concerns however,

- All of the tests are GET requests which might cause us to miss the performance degradation of any  DELETE, POST or PUT requests, whilst we don't have any current special processing for different request methods I think adding some more cases to cover the different methods would cover us for any potential future changes to that.

- The jobs requests tests are using system resources rather than resources we control, I saw you were using the SDSF Job for a lot of tests, maybe this is my lack of knowledge but I'm concerned that this Job might be quite active on a system and the job spool would change perhaps significantly between concurrent requests and even between test runs?  (Related: I see the dataset tests use the SYS1.HELP PDS which I assume never changes so shouldn't be a concern? same story for the host file you use for the unix file contants?)

**Comment by CaretCake** [comment]
> @CaretCake The test cases thus far look great, I have a couple of concerns however,
> 
> * All of the tests are GET requests which might cause us to miss the performance degradation of any  DELETE, POST or PUT requests, whilst we don't have any current special processing for different request methods I think adding some more cases to cover the different methods would cover us for any potential future changes to that.

@jordanCain I think that's reasonable to add test cases to cover other request types. For something like updating we should be able to do that with clean up rather simply. For creating and deleting, it's a little more complicated as we need to create the thing each time the test is run for it to be deleted again and vice versa, so it makes the most sense if we can test those together as a sequential endpoint test where each run of the test creates then deletes a file. Does that seem fine to you?

And then the follow-up to that is, of course, which endpoints do you think are most valuable for us to add these further test cases for?

> * The jobs requests tests are using system resources rather than resources we control, I saw you were using the SDSF Job for a lot of tests, maybe this is my lack of knowledge but I'm concerned that this Job might be quite active on a system and the job spool would change perhaps significantly between concurrent requests and even between test runs?  (Related: I see the dataset tests use the SYS1.HELP PDS which I assume never changes so shouldn't be a concern? same story for the host file you use for the unix file contants?)

Using the SDSF job and the datasets/files we chose were to increase the likelihood that the test cases could be pulled and run against anyone's system without issue or initial setup. This was more important for the primary test suite, and we do have more room to do things like create files specifically for testing, etc with the component test suites. That said, https://github.com/zowe/zowe-install-packaging/issues/633 covers the next steps of creating tests where we can compare pulling different file sizes, etc. I think that when we move on to working on this issue, we'll also be addressing your concerns here.

**Comment by jordanCain** [comment]
@CaretCake Thanks, I appreciate the additional complexity in the tests that would require creation/deletion of assets.

The other endpoints I think would be good to test, perhaps the PUT ones could be included in this suite and the others taken into account for the component level tests:
PUT:
Update unix file contents
Update datasets contents/ Update dataset member contents

POST:
Create dataset/create dataset member
Create unix file
Submit job to JES

DELETE:
Delete dataset/delete dataset member
Delete unix file
Purge Job

**Comment by CaretCake** [comment]
@jordanCain Thank you for the list! I think it's reasonable to include all of the above in this test suite.

Same as before, I think the PUT requests will be easily doable with standalone tests so we should be set there.

For POST/DELETE, we should be able to do these following combinations as sequential endpoint tests (each run of the test will create and delete, then repeat):
- create dataset + delete dataset
- create dataset member + delete dataset member
- create unix file + delete unix file

After discussing with Jack, the submit and purge job case warrants a bit more discussion. Since it's an async process to submit the job, purging right away may do nothing and we can't keep submitting forever without purging since the spool can eventually fill. Jack suggested setting a simple job (e.g. hello world), submit it 5 times, then purge once. It would be another sequential endpoint test (in this case, submit x5, purge, repeat). Does this plan seem reasonable to you? And, of course, we're open to other ideas if you have one.

**Comment by jordanCain** [comment]
@CaretCake Happy with everything you've suggested thus far. 

For the submit and purge jobs my proposal would be similar to how we handle this problem in the integration test suite we have; for testing submit we make an initial request and then go to a polling functions that's waiting for the job to appear in JES, as a job can be in multiple states such as QUEUED, ACTIVE, OUTPUT etc. at any point a job appears with any of that status the API has functioned correctly, i.e we don't need the job to be actively running for a positive result. So you could submit 10 jobs at once, and then poll for those 10 jobs to appear. If you submit all the jobs with the same name, assuming you start with a clean system with no existing jobs with that name you could use the get jobs endpoint and filter for the prefix of that job name and wait for the 10 jobs to appear in that response? 

And for the purge test I think you could build on top of the aforementioned functionality of waiting for 10 jobs to be submitted and then issue the 10 purge requests all at once and poll until all 10 jobs no longer appear in the filtered get jobs request response.

If this isn't clear please let me know, we can have a call or something to talk through, or if you have any other suggestions/concerns around this let me know

**Comment by CaretCake** [comment]
@jordanCain Thank you for the input - I think we have some more discussion to do on it. I'll set up a quick call for us and Jack so we can hash out the details.

**Comment by CaretCake** [comment]
Based on the discussion during our meeting, I'll be implementing the following test cases to add to this test suite:
- [ ] update unix file contents
- [ ] update dataset/dataset member contents
- [ ] create dataset + delete dataset
- [ ] create dataset member + delete dataset member
- [ ] create unix file + delete unix file

And investigating the following to see what our options are for implementation:
- [ ] submit job

**Comment by CaretCake** [comment]
I've completed the additional test cases requested for the test suite and they're ready for review.

Some clean up with a function @jackjia-ibm is currently working on will want to be added to explorer-apis/default/v2/post-job-string.ts, but it is otherwise ready to go.

**Review by jackjia-ibm — APPROVED** [review]
Great work! Thanks Melissa!

**Review by jordanCain — APPROVED** [review]
Looks great to me!

**Pull request merged**
